SELECT I2.ITEM_ID, I2.ITEM_NAME, I2.RARITY
FROM ITEM_INFO AS I
LEFT JOIN ITEM_TREE AS IT ON I.ITEM_ID = IT.PARENT_ITEM_ID
LEFT JOIN ITEM_INFO AS I2 ON IT.ITEM_ID = I2.ITEM_ID
WHERE I.RARITY = 'RARE' AND IT.PARENT_ITEM_ID IS NOT NULL
ORDER BY I2.ITEM_ID DESC





